# Generated by Django 3.2.13 on 2022-06-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature1a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('data_mode', models.CharField(default='A', max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
